### ISSUE TITLE
when i use ImmutableCardSet.empty(), it will crash

### ISSUE THREAD

**Issue by zhanzhenchao** [axross/poker#13]
```
final evaluator = ExhaustiveEvaluator(
    communityCards: ImmutableCardSet.empty(), players: handranges
);
```

**Comment by axross** [comment]
Thanks for the catch! I will look into it

**Comment by axross** [comment]
I tested with [4b51270cf77d14dbaa3aa0ce904b20469d57c2d7](https://github.com/axross/poker/tree/4b51270cf77d14dbaa3aa0ce904b20469d57c2d7) but it works without exception.

Note that using `ExhaustiveEvaluator` empty community card takes possibly up to `52 * 51 * 50 * 49 * 48` times than full community cards.
